//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated (once) by \generate-code.bat, but will not be
//     regenerated when it already exists. The purpose of creating this file is to make 
//     it easier to remember to implement all the unit conversion test cases.
// 
//     Whenever a new unit is added to this quantity and \generate-code.bat is run,
//     the base test class will get a new abstract property and cause a compile error
//     in this derived class, reminding the developer to implement the test case
//     for the new unit.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add Extensions\MyQuantityExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.


using System;

namespace UnitsNet.Tests.CustomCode
{
    public class JerkTests : JerkTestsBase
    {
        // TODO Override properties in base class here
        protected override double CentimetersPerSecondCubedInOneMeterPerSecondCubed => 1E2;

        protected override double DecimetersPerSecondCubedInOneMeterPerSecondCubed => 1E1;

        protected override double FeetPerSecondCubedInOneMeterPerSecondCubed => 3.28084;

        protected override double InchesPerSecondCubedInOneMeterPerSecondCubed => 39.3700787;

        protected override double KilometersPerSecondCubedInOneMeterPerSecondCubed => 1E-3;

        protected override double KnotsPerHourSquaredInOneMeterPerSecondCubed => 6.99784017278618E3;

        protected override double KnotsPerMinuteSquaredInOneMeterPerSecondCubed => 1.16630669546436E2;

        protected override double KnotsPerSecondSquaredInOneMeterPerSecondCubed => 1.94384449244060;

        protected override double MetersPerSecondCubedInOneMeterPerSecondCubed => 1;

        protected override double MicrometersPerSecondCubedInOneMeterPerSecondCubed => 1E6;

        protected override double MillimetersPerSecondCubedInOneMeterPerSecondCubed => 1E3;

        protected override double NanometersPerSecondCubedInOneMeterPerSecondCubed => 1E9;

        protected override double StandardGravityPerSecondInOneMeterPerSecondCubed => 1.019716212977928e-1;
    }
}
