//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add Extensions\MyQuantityExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Linq;
using JetBrains.Annotations;
using UnitsNet.Units;

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <summary>
    ///     Jerk is the rate at which the acceleration of an object changes over time.
    /// </summary>
    // ReSharper disable once PartialTypeWithSinglePart

    // Windows Runtime Component has constraints on public types: https://msdn.microsoft.com/en-us/library/br230301.aspx#Declaring types in Windows Runtime Components
    // Public structures can't have any members other than public fields, and those fields must be value types or strings.
    // Public classes must be sealed (NotInheritable in Visual Basic). If your programming model requires polymorphism, you can create a public interface and implement that interface on the classes that must be polymorphic.
#if WINDOWS_UWP
    public sealed partial class Jerk : IQuantity
#else
    public partial struct Jerk : IQuantity, IComparable, IComparable<Jerk>
#endif
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        private readonly double _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        private readonly JerkUnit? _unit;

        /// <summary>
        ///     The unit this quantity was constructed with -or- <see cref="BaseUnit" /> if default ctor was used.
        /// </summary>
        public JerkUnit Unit => _unit.GetValueOrDefault(BaseUnit);

        static Jerk()
        {
            BaseDimensions = new BaseDimensions(1, 0, -3, 0, 0, 0, 0);
        }

        [Obsolete("Use the constructor that takes a unit parameter. This constructor will be removed in a future version.")]
        public Jerk(double meterspersecondcubed)
        {
            _value = Convert.ToDouble(meterspersecondcubed);
            _unit = BaseUnit;
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="numericValue">Numeric value.</param>
        /// <param name="unit">Unit representation.</param>
        /// <remarks>Value parameter cannot be named 'value' due to constraint when targeting Windows Runtime Component.</remarks>
#if WINDOWS_UWP
        private
#else
        public 
#endif
        Jerk(double numericValue, JerkUnit unit)
        {
            _value = numericValue;
            _unit = unit;
        }

        // Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
        /// <summary>
        ///     Creates the quantity with the given value assuming the base unit MeterPerSecondCubed.
        /// </summary>
        /// <param name="meterspersecondcubed">Value assuming base unit MeterPerSecondCubed.</param>
#if WINDOWS_UWP
        private
#else
        [Obsolete("Use the constructor that takes a unit parameter. This constructor will be removed in a future version.")]
        public
#endif
        Jerk(long meterspersecondcubed) : this(Convert.ToDouble(meterspersecondcubed), BaseUnit) { }

        // Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
        // Windows Runtime Component does not support decimal type
        /// <summary>
        ///     Creates the quantity with the given value assuming the base unit MeterPerSecondCubed.
        /// </summary>
        /// <param name="meterspersecondcubed">Value assuming base unit MeterPerSecondCubed.</param>
#if WINDOWS_UWP
        private
#else
        [Obsolete("Use the constructor that takes a unit parameter. This constructor will be removed in a future version.")]
        public
#endif
        Jerk(decimal meterspersecondcubed) : this(Convert.ToDouble(meterspersecondcubed), BaseUnit) { }

        #region Properties

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        public static QuantityType QuantityType => QuantityType.Jerk;

        /// <summary>
        ///     The base unit representation of this quantity for the numeric value stored internally. All conversions go via this value.
        /// </summary>
        public static JerkUnit BaseUnit => JerkUnit.MeterPerSecondCubed;

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions
        {
            get;
        }

        /// <summary>
        ///     All units of measurement for the Jerk quantity.
        /// </summary>
        public static JerkUnit[] Units { get; } = Enum.GetValues(typeof(JerkUnit)).Cast<JerkUnit>().ToArray();

        /// <summary>
        ///     Get Jerk in CentimetersPerSecondCubed.
        /// </summary>
        public double CentimetersPerSecondCubed => As(JerkUnit.CentimeterPerSecondCubed);

        /// <summary>
        ///     Get Jerk in DecimetersPerSecondCubed.
        /// </summary>
        public double DecimetersPerSecondCubed => As(JerkUnit.DecimeterPerSecondCubed);

        /// <summary>
        ///     Get Jerk in FeetPerSecondCubed.
        /// </summary>
        public double FeetPerSecondCubed => As(JerkUnit.FootPerSecondCubed);

        /// <summary>
        ///     Get Jerk in InchesPerSecondCubed.
        /// </summary>
        public double InchesPerSecondCubed => As(JerkUnit.InchPerSecondCubed);

        /// <summary>
        ///     Get Jerk in KilometersPerSecondCubed.
        /// </summary>
        public double KilometersPerSecondCubed => As(JerkUnit.KilometerPerSecondCubed);

        /// <summary>
        ///     Get Jerk in KnotsPerHourSquared.
        /// </summary>
        public double KnotsPerHourSquared => As(JerkUnit.KnotPerHourSquared);

        /// <summary>
        ///     Get Jerk in KnotsPerMinuteSquared.
        /// </summary>
        public double KnotsPerMinuteSquared => As(JerkUnit.KnotPerMinuteSquared);

        /// <summary>
        ///     Get Jerk in KnotsPerSecondSquared.
        /// </summary>
        public double KnotsPerSecondSquared => As(JerkUnit.KnotPerSecondSquared);

        /// <summary>
        ///     Get Jerk in MetersPerSecondCubed.
        /// </summary>
        public double MetersPerSecondCubed => As(JerkUnit.MeterPerSecondCubed);

        /// <summary>
        ///     Get Jerk in MicrometersPerSecondCubed.
        /// </summary>
        public double MicrometersPerSecondCubed => As(JerkUnit.MicrometerPerSecondCubed);

        /// <summary>
        ///     Get Jerk in MillimetersPerSecondCubed.
        /// </summary>
        public double MillimetersPerSecondCubed => As(JerkUnit.MillimeterPerSecondCubed);

        /// <summary>
        ///     Get Jerk in NanometersPerSecondCubed.
        /// </summary>
        public double NanometersPerSecondCubed => As(JerkUnit.NanometerPerSecondCubed);

        /// <summary>
        ///     Get Jerk in StandardGravityPerSecond.
        /// </summary>
        public double StandardGravityPerSecond => As(JerkUnit.StandardGravityPerSecond);

        #endregion

        #region Static

        public static Jerk Zero => new Jerk(0, BaseUnit);

        /// <summary>
        ///     Get Jerk from CentimetersPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromCentimetersPerSecondCubed(double centimeterspersecondcubed)
#else
        public static Jerk FromCentimetersPerSecondCubed(QuantityValue centimeterspersecondcubed)
#endif
        {
            double value = (double) centimeterspersecondcubed;
            return new Jerk(value, JerkUnit.CentimeterPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from DecimetersPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromDecimetersPerSecondCubed(double decimeterspersecondcubed)
#else
        public static Jerk FromDecimetersPerSecondCubed(QuantityValue decimeterspersecondcubed)
#endif
        {
            double value = (double) decimeterspersecondcubed;
            return new Jerk(value, JerkUnit.DecimeterPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from FeetPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromFeetPerSecondCubed(double feetpersecondcubed)
#else
        public static Jerk FromFeetPerSecondCubed(QuantityValue feetpersecondcubed)
#endif
        {
            double value = (double) feetpersecondcubed;
            return new Jerk(value, JerkUnit.FootPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from InchesPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromInchesPerSecondCubed(double inchespersecondcubed)
#else
        public static Jerk FromInchesPerSecondCubed(QuantityValue inchespersecondcubed)
#endif
        {
            double value = (double) inchespersecondcubed;
            return new Jerk(value, JerkUnit.InchPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from KilometersPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromKilometersPerSecondCubed(double kilometerspersecondcubed)
#else
        public static Jerk FromKilometersPerSecondCubed(QuantityValue kilometerspersecondcubed)
#endif
        {
            double value = (double) kilometerspersecondcubed;
            return new Jerk(value, JerkUnit.KilometerPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from KnotsPerHourSquared.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromKnotsPerHourSquared(double knotsperhoursquared)
#else
        public static Jerk FromKnotsPerHourSquared(QuantityValue knotsperhoursquared)
#endif
        {
            double value = (double) knotsperhoursquared;
            return new Jerk(value, JerkUnit.KnotPerHourSquared);
        }

        /// <summary>
        ///     Get Jerk from KnotsPerMinuteSquared.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromKnotsPerMinuteSquared(double knotsperminutesquared)
#else
        public static Jerk FromKnotsPerMinuteSquared(QuantityValue knotsperminutesquared)
#endif
        {
            double value = (double) knotsperminutesquared;
            return new Jerk(value, JerkUnit.KnotPerMinuteSquared);
        }

        /// <summary>
        ///     Get Jerk from KnotsPerSecondSquared.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromKnotsPerSecondSquared(double knotspersecondsquared)
#else
        public static Jerk FromKnotsPerSecondSquared(QuantityValue knotspersecondsquared)
#endif
        {
            double value = (double) knotspersecondsquared;
            return new Jerk(value, JerkUnit.KnotPerSecondSquared);
        }

        /// <summary>
        ///     Get Jerk from MetersPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromMetersPerSecondCubed(double meterspersecondcubed)
#else
        public static Jerk FromMetersPerSecondCubed(QuantityValue meterspersecondcubed)
#endif
        {
            double value = (double) meterspersecondcubed;
            return new Jerk(value, JerkUnit.MeterPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from MicrometersPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromMicrometersPerSecondCubed(double micrometerspersecondcubed)
#else
        public static Jerk FromMicrometersPerSecondCubed(QuantityValue micrometerspersecondcubed)
#endif
        {
            double value = (double) micrometerspersecondcubed;
            return new Jerk(value, JerkUnit.MicrometerPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from MillimetersPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromMillimetersPerSecondCubed(double millimeterspersecondcubed)
#else
        public static Jerk FromMillimetersPerSecondCubed(QuantityValue millimeterspersecondcubed)
#endif
        {
            double value = (double) millimeterspersecondcubed;
            return new Jerk(value, JerkUnit.MillimeterPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from NanometersPerSecondCubed.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromNanometersPerSecondCubed(double nanometerspersecondcubed)
#else
        public static Jerk FromNanometersPerSecondCubed(QuantityValue nanometerspersecondcubed)
#endif
        {
            double value = (double) nanometerspersecondcubed;
            return new Jerk(value, JerkUnit.NanometerPerSecondCubed);
        }

        /// <summary>
        ///     Get Jerk from StandardGravityPerSecond.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static Jerk FromStandardGravityPerSecond(double standardgravitypersecond)
#else
        public static Jerk FromStandardGravityPerSecond(QuantityValue standardgravitypersecond)
#endif
        {
            double value = (double) standardgravitypersecond;
            return new Jerk(value, JerkUnit.StandardGravityPerSecond);
        }


        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="JerkUnit" /> to <see cref="Jerk" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>Jerk unit value.</returns>
#if WINDOWS_UWP
        // Fix name conflict with parameter "value"
        [return: System.Runtime.InteropServices.WindowsRuntime.ReturnValueName("returnValue")]
        public static Jerk From(double value, JerkUnit fromUnit)
#else
        public static Jerk From(QuantityValue value, JerkUnit fromUnit)
#endif
        {
            return new Jerk((double)value, fromUnit);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [UsedImplicitly]
        public static string GetAbbreviation(JerkUnit unit)
        {
            return GetAbbreviation(unit, null);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
#if WINDOWS_UWP
        /// <param name="cultureName">Name of culture (ex: "en-US") to use for localization. Defaults to <see cref="UnitSystem" />'s default culture.</param>
#else
        /// <param name="provider">Format to use for localization. Defaults to <see cref="UnitSystem.DefaultCulture" />.</param>
#endif
        /// <returns>Unit abbreviation string.</returns>
        [UsedImplicitly]
        public static string GetAbbreviation(
          JerkUnit unit,
#if WINDOWS_UWP
          [CanBeNull] string cultureName)
#else
          [CanBeNull] IFormatProvider provider)
#endif
        {
#if WINDOWS_UWP
            // Windows Runtime Component does not support CultureInfo and IFormatProvider types, so we use culture name for public methods: https://msdn.microsoft.com/en-us/library/br230301.aspx
            IFormatProvider provider = cultureName == null ? UnitSystem.DefaultCulture : new CultureInfo(cultureName);
#else
            provider = provider ?? UnitSystem.DefaultCulture;
#endif

            return UnitSystem.GetCached(provider).GetDefaultAbbreviation(unit);
        }

        #endregion

        #region Equality / IComparable

        public int CompareTo(object obj)
        {
            if(obj is null) throw new ArgumentNullException(nameof(obj));
            if(!(obj is Jerk)) throw new ArgumentException("Expected type Jerk.", nameof(obj));

            return CompareTo((Jerk)obj);
        }

        // Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
#if WINDOWS_UWP
        internal
#else
        public
#endif
        int CompareTo(Jerk other)
        {
            return _value.CompareTo(other.AsBaseNumericType(this.Unit));
        }

        [Obsolete("It is not safe to compare equality due to using System.Double as the internal representation. It is very easy to get slightly different values due to floating point operations. Instead use Equals($quantityName, double, ComparisonType) to provide the max allowed absolute or relative error.")]
        public override bool Equals(object obj)
        {
            if(obj is null || !(obj is Jerk))
                return false;

            var objQuantity = (Jerk)obj;
            return _value.Equals(objQuantity.AsBaseNumericType(this.Unit));
        }

        /// <summary>
        ///     <para>
        ///     Compare equality to another Jerk within the given absolute or relative tolerance.
        ///     </para>
        ///     <para>
        ///     Relative tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a percentage of this quantity's value. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison. A relative tolerance of 0.01 means the absolute difference must be within +/- 1% of
        ///     this quantity's value to be considered equal.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within +/- 1% of a (0.02m or 2cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Relative);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Absolute tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a fixed number in this quantity's unit. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within 0.01 of a (0.01m or 1cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Absolute);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Note that it is advised against specifying zero difference, due to the nature
        ///     of floating point operations and using System.Double internally.
        ///     </para>
        /// </summary>
        /// <param name="other">The other quantity to compare to.</param>
        /// <param name="tolerance">The absolute or relative tolerance value. Must be greater than or equal to 0.</param>
        /// <param name="comparisonType">The comparison type: either relative or absolute.</param>
        /// <returns>True if the absolute difference between the two values is not greater than the specified relative or absolute tolerance.</returns>
        public bool Equals(Jerk other, double tolerance, ComparisonType comparisonType)
        {
            if(tolerance < 0)
                throw new ArgumentOutOfRangeException("tolerance", "Tolerance must be greater than or equal to 0.");

            double thisValue = (double)this.Value;
            double otherValueInThisUnits = other.As(this.Unit);

            return UnitsNet.Comparison.Equals(thisValue, otherValueInThisUnits, tolerance, comparisonType);
        }

        /// <summary>
        ///     Compare equality to another Jerk by specifying a max allowed difference.
        ///     Note that it is advised against specifying zero difference, due to the nature
        ///     of floating point operations and using System.Double internally.
        /// </summary>
        /// <param name="other">Other quantity to compare to.</param>
        /// <param name="maxError">Max error allowed.</param>
        /// <returns>True if the difference between the two values is not greater than the specified max.</returns>
        [Obsolete("Please use the Equals(Jerk, double, ComparisonType) overload. This method will be removed in a future version.")]
        public bool Equals(Jerk other, Jerk maxError)
        {
            return Math.Abs(_value - other.AsBaseNumericType(this.Unit)) <= maxError.AsBaseNumericType(this.Unit);
        }

        public override int GetHashCode()
        {
            return new { Value, Unit }.GetHashCode();
        }

        #endregion

        #region Conversion

        /// <summary>
        ///     Convert to the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>Value converted to the specified unit.</returns>
        public double As(JerkUnit unit)
        {
            if(Unit == unit)
                return Convert.ToDouble(Value);

            var converted = AsBaseNumericType(unit);
            return Convert.ToDouble(converted);
        }

        /// <summary>
        ///     Converts this Jerk to another Jerk with the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>A Jerk with the specified unit.</returns>
        public Jerk ToUnit(JerkUnit unit)
        {
            var convertedValue = AsBaseNumericType(unit);
            return new Jerk(convertedValue, unit);
        }

        /// <summary>
        ///     Converts the current value + unit to the base unit.
        ///     This is typically the first step in converting from one unit to another.
        /// </summary>
        /// <returns>The value in the base unit representation.</returns>
        private double AsBaseUnit()
        {
            switch(Unit)
            {
                case JerkUnit.CentimeterPerSecondCubed: return (_value) * 1e-2d;
                case JerkUnit.DecimeterPerSecondCubed: return (_value) * 1e-1d;
                case JerkUnit.FootPerSecondCubed: return _value*0.304800;
                case JerkUnit.InchPerSecondCubed: return _value*0.0254;
                case JerkUnit.KilometerPerSecondCubed: return (_value) * 1e3d;
                case JerkUnit.KnotPerHourSquared: return _value*0.5144444444444/3600;
                case JerkUnit.KnotPerMinuteSquared: return _value*0.5144444444444/60;
                case JerkUnit.KnotPerSecondSquared: return _value*0.5144444444444;
                case JerkUnit.MeterPerSecondCubed: return _value;
                case JerkUnit.MicrometerPerSecondCubed: return (_value) * 1e-6d;
                case JerkUnit.MillimeterPerSecondCubed: return (_value) * 1e-3d;
                case JerkUnit.NanometerPerSecondCubed: return (_value) * 1e-9d;
                case JerkUnit.StandardGravityPerSecond: return _value*9.80665;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to base units.");
            }
        }

        private double AsBaseNumericType(JerkUnit unit)
        {
            if(Unit == unit)
                return _value;

            var baseUnitValue = AsBaseUnit();

            switch(unit)
            {
                case JerkUnit.CentimeterPerSecondCubed: return (baseUnitValue) / 1e-2d;
                case JerkUnit.DecimeterPerSecondCubed: return (baseUnitValue) / 1e-1d;
                case JerkUnit.FootPerSecondCubed: return baseUnitValue/0.304800;
                case JerkUnit.InchPerSecondCubed: return baseUnitValue/0.0254;
                case JerkUnit.KilometerPerSecondCubed: return (baseUnitValue) / 1e3d;
                case JerkUnit.KnotPerHourSquared: return baseUnitValue/0.5144444444444*3600;
                case JerkUnit.KnotPerMinuteSquared: return baseUnitValue/0.5144444444444*60;
                case JerkUnit.KnotPerSecondSquared: return baseUnitValue/0.5144444444444;
                case JerkUnit.MeterPerSecondCubed: return baseUnitValue;
                case JerkUnit.MicrometerPerSecondCubed: return (baseUnitValue) / 1e-6d;
                case JerkUnit.MillimeterPerSecondCubed: return (baseUnitValue) / 1e-3d;
                case JerkUnit.NanometerPerSecondCubed: return (baseUnitValue) / 1e-9d;
                case JerkUnit.StandardGravityPerSecond: return baseUnitValue/9.80665;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to {unit}.");
            }
        }

        #endregion

        #region Parsing

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        public static Jerk Parse(string str)
        {
            return Parse(str, null);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        public static bool TryParse([CanBeNull] string str, out Jerk result)
        {
            return TryParse(str, null, out result);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static JerkUnit ParseUnit(string str)
        {
            return ParseUnit(str, (IFormatProvider)null);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="cultureName">Name of culture (ex: "en-US") to use when parsing number and unit. Defaults to <see cref="UnitSystem" />'s default culture.</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        [Obsolete("Use overload that takes IFormatProvider instead of culture name. This method was only added to support WindowsRuntimeComponent and will be removed from other .NET targets.")]
        public static JerkUnit ParseUnit(string str, [CanBeNull] string cultureName)
        {
            return ParseUnit(str, cultureName == null ? null : new CultureInfo(cultureName));
        }

        #endregion

        [Obsolete("This is no longer used since we will instead use the quantity's Unit value as default.")]
        /// <summary>
        ///     Set the default unit used by ToString(). Default is MeterPerSecondCubed
        /// </summary>
        public static JerkUnit ToStringDefaultUnit { get; set; } = JerkUnit.MeterPerSecondCubed;

        /// <summary>
        ///     Get default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
        {
            return ToString(Unit);
        }

        /// <summary>
        ///     Get string representation of value and unit. Using current UI culture and two significant digits after radix.
        /// </summary>
        /// <param name="unit">Unit representation to use.</param>
        /// <returns>String representation.</returns>
        public string ToString(JerkUnit unit)
        {
            return ToString(unit, null, 2);
        }

        /// <summary>
        /// Represents the largest possible value of Jerk
        /// </summary>
        public static Jerk MaxValue => new Jerk(double.MaxValue, BaseUnit);

        /// <summary>
        /// Represents the smallest possible value of Jerk
        /// </summary>
        public static Jerk MinValue => new Jerk(double.MinValue, BaseUnit);

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        public QuantityType Type => Jerk.QuantityType;

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public BaseDimensions Dimensions => Jerk.BaseDimensions;
    }
}
